# ================================
# .streamlit/config.toml
# ANWW DuikApp - kleurthema
# ================================

[theme]
# Basis Streamlit kleuren
primaryColor = "#728DCC"              # primaire knopkleur
backgroundColor = "#8DAEBA"           # algemene achtergrond
secondaryBackgroundColor = "#A38B16"  # panelen / expanders / tabs
textColor = "#11064D"                 # hoofdtekst
font = "sans serif"

