# ================================
# .streamlit/config.toml
# ANWW DuikApp - kleurthema
# ================================

[theme]
primaryColor = "#728DCC"
backgroundColor = "#8DAEBA"
secondaryBackgroundColor = "#A38B16"
textColor = "#11064D"
font = "sans serif"


