[supabase]
url = "https://eqynyshmhbxmywmbqmot.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxeW55c2htaGJ4bXl3bWJxbW90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4Njk4NzUsImV4cCI6MjA3MzQ0NTg3NX0.dLtg-BecQqSvsKaNFoyzlGJzkVsWVp0BbE2ZweLBGGw"
[theme]
bg = "#8DAEBA"
surface = "#99883F"
card = "#A38B16"
border = "#2a355a"
text = "##11064D"
muted = "#9fb0d9"
primary = "#728DCC"
primary_contrast = "#453A06"
accent = "#22d3ee"
success = "#3CA133"
warning = "#f59e0b"
error = "#ef4444"
[theme]
backgroundColor="#9bb7ef"
secondaryBackgroundColor="#779465"
textColor="#1b0a92"
