[supabase]
url = "https://fglesklfcejzkofnsxmq.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnbGVza2xmY2VqemtvZm5zeG1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMTI2ODAsImV4cCI6MjA3MzY4ODY4MH0.DOu-1dJEPt6lZQdELmzor3mr496GsASjB52ZQIVEL9A"


