[supabase]
url = "https://fglesklfcejzkofnsxmq.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnbGVza2xmY2VqemtvZm5zeG1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMTI2ODAsImV4cCI6MjA3MzY4ODY4MH0.DOu-1dJEPt6lZQdELmzor3mr496GsASjB52ZQIVEL9A"

[app]
force_readonly = false  # optioneel noodslot

[theme]  # ← dit is de app-thema sectie die mijn code leest
bg = "#8DAEBA"
surface = "#99883F"
card = "#A38B16"
border = "#2a355a"
text = "#11064D"            # ← 1 hekje
muted = "#9fb0d9"
primary = "#728DCC"
primary_contrast = "#453A06"
accent = "#22d3ee"
success = "#3CA133"
warning = "#f59e0b"
error = "#ef4444"
